++++++++++[>+++++++>++++++++++>+++>+<<<<-]>++.>+.+++++++..+++.>++.
<<+++++++++++++++.>.+++.------.--------.>+.>.
mjUB5Xs4twJmunKWXT5ETCCahW9ybMQVsv
mhNzBLi64rWaGKBbbNu3mdgANFoihLbSbE
mhAzKYntxmtTw1qPCd74WLXVLW8FNwBkxY
mzyUEMcUxgoVcCFqsAuaouERbMVTFxNdKe
mjnCEevCX6LiyUhvrPbVSx448dNcTVrJhs
mjNBZrCg8YSCyPZs7aBxEceN2XwYDTU1Gm
mhLc5wGX9Grh7ixaqsXrFMzp1mf7B9M6Wu
mkd659VJmm6i5ybsnhKQ62o4KTqqYYreeH
mhSTysa4TtAoY3q1vydoahzDtqTTWHzmyh
mmm7tG8hr1s6UHrTwuvMSqbNW2BZ1GoGex
mwaj4WJb12aLM2dDxVVroGZrEoAc4S9fcW
